services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: mlops-backend
    ports:
      - "3001:3001"
    volumes:
      - ./Backend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: mlops-frontend
    ports:
      - "3000:80"
    volumes:
      - ./Frontend:/app

  mongo:
    image: mongo
    container_name: mlops-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
